/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import "Thrift/protocol/TProtocol.h"
#import "Thrift/TApplicationException.h"
#import "Thrift/protocol/TProtocolUtil.h"
#import "Thrift/TProcessor.h"


typedef NSArray * ProcessInfoList;

typedef NSArray * HogsBugsList;

typedef NSArray * FeatureList;

@interface Registration : NSObject <NSCoding> {
  NSString * __uuId;
  double __timestamp;
  NSString * __platformId;
  NSString * __systemVersion;

  BOOL __uuId_isset;
  BOOL __timestamp_isset;
  BOOL __platformId_isset;
  BOOL __systemVersion_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=uuId, setter=setUuId:) NSString * uuId;
@property (nonatomic, getter=timestamp, setter=setTimestamp:) double timestamp;
@property (nonatomic, retain, getter=platformId, setter=setPlatformId:) NSString * platformId;
@property (nonatomic, retain, getter=systemVersion, setter=setSystemVersion:) NSString * systemVersion;
#endif

- (id) initWithUuId: (NSString *) uuId timestamp: (double) timestamp platformId: (NSString *) platformId systemVersion: (NSString *) systemVersion;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) uuId;
- (void) setUuId: (NSString *) uuId;
- (BOOL) uuIdIsSet;

- (double) timestamp;
- (void) setTimestamp: (double) timestamp;
- (BOOL) timestampIsSet;

- (NSString *) platformId;
- (void) setPlatformId: (NSString *) platformId;
- (BOOL) platformIdIsSet;

- (NSString *) systemVersion;
- (void) setSystemVersion: (NSString *) systemVersion;
- (BOOL) systemVersionIsSet;

@end

@interface ProcessInfo : NSObject <NSCoding> {
  int32_t __pId;
  NSString * __pName;

  BOOL __pId_isset;
  BOOL __pName_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=pId, setter=setPId:) int32_t pId;
@property (nonatomic, retain, getter=pName, setter=setPName:) NSString * pName;
#endif

- (id) initWithPId: (int32_t) pId pName: (NSString *) pName;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (int32_t) pId;
- (void) setPId: (int32_t) pId;
- (BOOL) pIdIsSet;

- (NSString *) pName;
- (void) setPName: (NSString *) pName;
- (BOOL) pNameIsSet;

@end

@interface Sample : NSObject <NSCoding> {
  NSString * __uuId;
  double __timestamp;
  ProcessInfoList __piList;
  NSString * __batteryState;
  double __batteryLevel;
  int32_t __memoryWired;
  int32_t __memoryActive;
  int32_t __memoryInactive;
  int32_t __memoryFree;
  int32_t __memoryUser;
  NSString * __triggeredBy;
  NSString * __networkStatus;

  BOOL __uuId_isset;
  BOOL __timestamp_isset;
  BOOL __piList_isset;
  BOOL __batteryState_isset;
  BOOL __batteryLevel_isset;
  BOOL __memoryWired_isset;
  BOOL __memoryActive_isset;
  BOOL __memoryInactive_isset;
  BOOL __memoryFree_isset;
  BOOL __memoryUser_isset;
  BOOL __triggeredBy_isset;
  BOOL __networkStatus_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=uuId, setter=setUuId:) NSString * uuId;
@property (nonatomic, getter=timestamp, setter=setTimestamp:) double timestamp;
@property (nonatomic, retain, getter=piList, setter=setPiList:) ProcessInfoList piList;
@property (nonatomic, retain, getter=batteryState, setter=setBatteryState:) NSString * batteryState;
@property (nonatomic, getter=batteryLevel, setter=setBatteryLevel:) double batteryLevel;
@property (nonatomic, getter=memoryWired, setter=setMemoryWired:) int32_t memoryWired;
@property (nonatomic, getter=memoryActive, setter=setMemoryActive:) int32_t memoryActive;
@property (nonatomic, getter=memoryInactive, setter=setMemoryInactive:) int32_t memoryInactive;
@property (nonatomic, getter=memoryFree, setter=setMemoryFree:) int32_t memoryFree;
@property (nonatomic, getter=memoryUser, setter=setMemoryUser:) int32_t memoryUser;
@property (nonatomic, retain, getter=triggeredBy, setter=setTriggeredBy:) NSString * triggeredBy;
@property (nonatomic, retain, getter=networkStatus, setter=setNetworkStatus:) NSString * networkStatus;
#endif

- (id) initWithUuId: (NSString *) uuId timestamp: (double) timestamp piList: (ProcessInfoList) piList batteryState: (NSString *) batteryState batteryLevel: (double) batteryLevel memoryWired: (int32_t) memoryWired memoryActive: (int32_t) memoryActive memoryInactive: (int32_t) memoryInactive memoryFree: (int32_t) memoryFree memoryUser: (int32_t) memoryUser triggeredBy: (NSString *) triggeredBy networkStatus: (NSString *) networkStatus;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) uuId;
- (void) setUuId: (NSString *) uuId;
- (BOOL) uuIdIsSet;

- (double) timestamp;
- (void) setTimestamp: (double) timestamp;
- (BOOL) timestampIsSet;

- (ProcessInfoList) piList;
- (void) setPiList: (ProcessInfoList) piList;
- (BOOL) piListIsSet;

- (NSString *) batteryState;
- (void) setBatteryState: (NSString *) batteryState;
- (BOOL) batteryStateIsSet;

- (double) batteryLevel;
- (void) setBatteryLevel: (double) batteryLevel;
- (BOOL) batteryLevelIsSet;

- (int32_t) memoryWired;
- (void) setMemoryWired: (int32_t) memoryWired;
- (BOOL) memoryWiredIsSet;

- (int32_t) memoryActive;
- (void) setMemoryActive: (int32_t) memoryActive;
- (BOOL) memoryActiveIsSet;

- (int32_t) memoryInactive;
- (void) setMemoryInactive: (int32_t) memoryInactive;
- (BOOL) memoryInactiveIsSet;

- (int32_t) memoryFree;
- (void) setMemoryFree: (int32_t) memoryFree;
- (BOOL) memoryFreeIsSet;

- (int32_t) memoryUser;
- (void) setMemoryUser: (int32_t) memoryUser;
- (BOOL) memoryUserIsSet;

- (NSString *) triggeredBy;
- (void) setTriggeredBy: (NSString *) triggeredBy;
- (BOOL) triggeredByIsSet;

- (NSString *) networkStatus;
- (void) setNetworkStatus: (NSString *) networkStatus;
- (BOOL) networkStatusIsSet;

@end

@interface DetailScreenReport : NSObject <NSCoding> {
  double __score;
  NSArray * __xVals;
  NSArray * __yVals;
  double __expectedValue;

  BOOL __score_isset;
  BOOL __xVals_isset;
  BOOL __yVals_isset;
  BOOL __expectedValue_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=score, setter=setScore:) double score;
@property (nonatomic, retain, getter=xVals, setter=setXVals:) NSArray * xVals;
@property (nonatomic, retain, getter=yVals, setter=setYVals:) NSArray * yVals;
@property (nonatomic, getter=expectedValue, setter=setExpectedValue:) double expectedValue;
#endif

- (id) initWithScore: (double) score xVals: (NSArray *) xVals yVals: (NSArray *) yVals expectedValue: (double) expectedValue;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (double) score;
- (void) setScore: (double) score;
- (BOOL) scoreIsSet;

- (NSArray *) xVals;
- (void) setXVals: (NSArray *) xVals;
- (BOOL) xValsIsSet;

- (NSArray *) yVals;
- (void) setYVals: (NSArray *) yVals;
- (BOOL) yValsIsSet;

- (double) expectedValue;
- (void) setExpectedValue: (double) expectedValue;
- (BOOL) expectedValueIsSet;

@end

@interface Reports : NSObject <NSCoding> {
  double __jScore;
  DetailScreenReport * __os;
  DetailScreenReport * __osWithout;
  DetailScreenReport * __model;
  DetailScreenReport * __modelWithout;
  DetailScreenReport * __similarApps;
  DetailScreenReport * __similarAppsWithout;
  double __changeSinceLastWeek;
  double __changeSinceLastWeekPercentage;
  DetailScreenReport * __jScoreWith;
  DetailScreenReport * __jScoreWithout;

  BOOL __jScore_isset;
  BOOL __os_isset;
  BOOL __osWithout_isset;
  BOOL __model_isset;
  BOOL __modelWithout_isset;
  BOOL __similarApps_isset;
  BOOL __similarAppsWithout_isset;
  BOOL __changeSinceLastWeek_isset;
  BOOL __changeSinceLastWeekPercentage_isset;
  BOOL __jScoreWith_isset;
  BOOL __jScoreWithout_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=jScore, setter=setJScore:) double jScore;
@property (nonatomic, retain, getter=os, setter=setOs:) DetailScreenReport * os;
@property (nonatomic, retain, getter=osWithout, setter=setOsWithout:) DetailScreenReport * osWithout;
@property (nonatomic, retain, getter=model, setter=setModel:) DetailScreenReport * model;
@property (nonatomic, retain, getter=modelWithout, setter=setModelWithout:) DetailScreenReport * modelWithout;
@property (nonatomic, retain, getter=similarApps, setter=setSimilarApps:) DetailScreenReport * similarApps;
@property (nonatomic, retain, getter=similarAppsWithout, setter=setSimilarAppsWithout:) DetailScreenReport * similarAppsWithout;
@property (nonatomic, getter=changeSinceLastWeek, setter=setChangeSinceLastWeek:) double changeSinceLastWeek;
@property (nonatomic, getter=changeSinceLastWeekPercentage, setter=setChangeSinceLastWeekPercentage:) double changeSinceLastWeekPercentage;
@property (nonatomic, retain, getter=jScoreWith, setter=setJScoreWith:) DetailScreenReport * jScoreWith;
@property (nonatomic, retain, getter=jScoreWithout, setter=setJScoreWithout:) DetailScreenReport * jScoreWithout;
#endif

- (id) initWithJScore: (double) jScore os: (DetailScreenReport *) os osWithout: (DetailScreenReport *) osWithout model: (DetailScreenReport *) model modelWithout: (DetailScreenReport *) modelWithout similarApps: (DetailScreenReport *) similarApps similarAppsWithout: (DetailScreenReport *) similarAppsWithout changeSinceLastWeek: (double) changeSinceLastWeek changeSinceLastWeekPercentage: (double) changeSinceLastWeekPercentage jScoreWith: (DetailScreenReport *) jScoreWith jScoreWithout: (DetailScreenReport *) jScoreWithout;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (double) jScore;
- (void) setJScore: (double) jScore;
- (BOOL) jScoreIsSet;

- (DetailScreenReport *) os;
- (void) setOs: (DetailScreenReport *) os;
- (BOOL) osIsSet;

- (DetailScreenReport *) osWithout;
- (void) setOsWithout: (DetailScreenReport *) osWithout;
- (BOOL) osWithoutIsSet;

- (DetailScreenReport *) model;
- (void) setModel: (DetailScreenReport *) model;
- (BOOL) modelIsSet;

- (DetailScreenReport *) modelWithout;
- (void) setModelWithout: (DetailScreenReport *) modelWithout;
- (BOOL) modelWithoutIsSet;

- (DetailScreenReport *) similarApps;
- (void) setSimilarApps: (DetailScreenReport *) similarApps;
- (BOOL) similarAppsIsSet;

- (DetailScreenReport *) similarAppsWithout;
- (void) setSimilarAppsWithout: (DetailScreenReport *) similarAppsWithout;
- (BOOL) similarAppsWithoutIsSet;

- (double) changeSinceLastWeek;
- (void) setChangeSinceLastWeek: (double) changeSinceLastWeek;
- (BOOL) changeSinceLastWeekIsSet;

- (double) changeSinceLastWeekPercentage;
- (void) setChangeSinceLastWeekPercentage: (double) changeSinceLastWeekPercentage;
- (BOOL) changeSinceLastWeekPercentageIsSet;

- (DetailScreenReport *) jScoreWith;
- (void) setJScoreWith: (DetailScreenReport *) jScoreWith;
- (BOOL) jScoreWithIsSet;

- (DetailScreenReport *) jScoreWithout;
- (void) setJScoreWithout: (DetailScreenReport *) jScoreWithout;
- (BOOL) jScoreWithoutIsSet;

@end

@interface HogsBugs : NSObject <NSCoding> {
  NSString * __appName;
  double __wDistance;
  NSArray * __xVals;
  NSArray * __yVals;
  NSArray * __xValsWithout;
  NSArray * __yValsWithout;
  double __expectedValue;
  double __expectedValueWithout;

  BOOL __appName_isset;
  BOOL __wDistance_isset;
  BOOL __xVals_isset;
  BOOL __yVals_isset;
  BOOL __xValsWithout_isset;
  BOOL __yValsWithout_isset;
  BOOL __expectedValue_isset;
  BOOL __expectedValueWithout_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=appName, setter=setAppName:) NSString * appName;
@property (nonatomic, getter=wDistance, setter=setWDistance:) double wDistance;
@property (nonatomic, retain, getter=xVals, setter=setXVals:) NSArray * xVals;
@property (nonatomic, retain, getter=yVals, setter=setYVals:) NSArray * yVals;
@property (nonatomic, retain, getter=xValsWithout, setter=setXValsWithout:) NSArray * xValsWithout;
@property (nonatomic, retain, getter=yValsWithout, setter=setYValsWithout:) NSArray * yValsWithout;
@property (nonatomic, getter=expectedValue, setter=setExpectedValue:) double expectedValue;
@property (nonatomic, getter=expectedValueWithout, setter=setExpectedValueWithout:) double expectedValueWithout;
#endif

- (id) initWithAppName: (NSString *) appName wDistance: (double) wDistance xVals: (NSArray *) xVals yVals: (NSArray *) yVals xValsWithout: (NSArray *) xValsWithout yValsWithout: (NSArray *) yValsWithout expectedValue: (double) expectedValue expectedValueWithout: (double) expectedValueWithout;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) appName;
- (void) setAppName: (NSString *) appName;
- (BOOL) appNameIsSet;

- (double) wDistance;
- (void) setWDistance: (double) wDistance;
- (BOOL) wDistanceIsSet;

- (NSArray *) xVals;
- (void) setXVals: (NSArray *) xVals;
- (BOOL) xValsIsSet;

- (NSArray *) yVals;
- (void) setYVals: (NSArray *) yVals;
- (BOOL) yValsIsSet;

- (NSArray *) xValsWithout;
- (void) setXValsWithout: (NSArray *) xValsWithout;
- (BOOL) xValsWithoutIsSet;

- (NSArray *) yValsWithout;
- (void) setYValsWithout: (NSArray *) yValsWithout;
- (BOOL) yValsWithoutIsSet;

- (double) expectedValue;
- (void) setExpectedValue: (double) expectedValue;
- (BOOL) expectedValueIsSet;

- (double) expectedValueWithout;
- (void) setExpectedValueWithout: (double) expectedValueWithout;
- (BOOL) expectedValueWithoutIsSet;

@end

@interface HogBugReport : NSObject <NSCoding> {
  NSString * __uuId;
  HogsBugsList __hbList;

  BOOL __uuId_isset;
  BOOL __hbList_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=uuId, setter=setUuId:) NSString * uuId;
@property (nonatomic, retain, getter=hbList, setter=setHbList:) HogsBugsList hbList;
#endif

- (id) initWithUuId: (NSString *) uuId hbList: (HogsBugsList) hbList;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) uuId;
- (void) setUuId: (NSString *) uuId;
- (BOOL) uuIdIsSet;

- (HogsBugsList) hbList;
- (void) setHbList: (HogsBugsList) hbList;
- (BOOL) hbListIsSet;

@end

@interface Feature : NSObject <NSCoding> {
  NSString * __key;
  NSString * __value;

  BOOL __key_isset;
  BOOL __value_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=key, setter=setKey:) NSString * key;
@property (nonatomic, retain, getter=value, setter=setValue:) NSString * value;
#endif

- (id) initWithKey: (NSString *) key value: (NSString *) value;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) key;
- (void) setKey: (NSString *) key;
- (BOOL) keyIsSet;

- (NSString *) value;
- (void) setValue: (NSString *) value;
- (BOOL) valueIsSet;

@end

@protocol CaratService <NSObject>
- (void) registerMe: (Registration *) registration;  // throws TException
- (BOOL) uploadSample: (Sample *) sample;  // throws TException
- (Reports *) getReports: (NSString *) uuId : (FeatureList) features;  // throws TException
- (HogBugReport *) getHogOrBugReport: (NSString *) uuId : (FeatureList) features;  // throws TException
@end

@interface CaratServiceClient : NSObject <CaratService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface CaratServiceProcessor : NSObject <TProcessor> {
  id <CaratService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithCaratService: (id <CaratService>) service;
- (id<CaratService>) service;
@end

@interface CaratProtocolConstants : NSObject {
}
@end
