#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/socialize/SocializeCocoaPods.git'

platform:ios, '8.0'
inhibit_all_warnings!

pod 'Socialize', :podspec => 'https://raw.github.com/socialize/socialize-sdk-ios/master/Socialize.podspec'
# Append to your Podfile
post_install do |installer_representation|
	installer_representation.project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
		end
	end
end