source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/socialize/SocializeCocoaPods.git'

platform:ios, '7.1'
inhibit_all_warnings!

pod 'Socialize', :podspec => 'https://raw.github.com/socialize/socialize-sdk-ios/master/Socialize.podspec'
