// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Sample;
@class Sample_Builder;
@class Samples;
@class Samples_Builder;

@interface CaratProtocolRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Sample : PBGeneratedMessage {
@private
  BOOL hasProcessId_:1;
  BOOL hasProcessName_:1;
  int32_t processId;
  NSString* processName;
}
- (BOOL) hasProcessId;
- (BOOL) hasProcessName;
@property (readonly) int32_t processId;
@property (readonly, retain) NSString* processName;

+ (Sample*) defaultInstance;
- (Sample*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Sample_Builder*) builder;
+ (Sample_Builder*) builder;
+ (Sample_Builder*) builderWithPrototype:(Sample*) prototype;

+ (Sample*) parseFromData:(NSData*) data;
+ (Sample*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Sample*) parseFromInputStream:(NSInputStream*) input;
+ (Sample*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Sample*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Sample*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Sample_Builder : PBGeneratedMessage_Builder {
@private
  Sample* result;
}

- (Sample*) defaultInstance;

- (Sample_Builder*) clear;
- (Sample_Builder*) clone;

- (Sample*) build;
- (Sample*) buildPartial;

- (Sample_Builder*) mergeFrom:(Sample*) other;
- (Sample_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Sample_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasProcessId;
- (int32_t) processId;
- (Sample_Builder*) setProcessId:(int32_t) value;
- (Sample_Builder*) clearProcessId;

- (BOOL) hasProcessName;
- (NSString*) processName;
- (Sample_Builder*) setProcessName:(NSString*) value;
- (Sample_Builder*) clearProcessName;
@end

@interface Samples : PBGeneratedMessage {
@private
  NSMutableArray* mutableSampleList;
}
- (NSArray*) sampleList;
- (Sample*) sampleAtIndex:(int32_t) index;

+ (Samples*) defaultInstance;
- (Samples*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Samples_Builder*) builder;
+ (Samples_Builder*) builder;
+ (Samples_Builder*) builderWithPrototype:(Samples*) prototype;

+ (Samples*) parseFromData:(NSData*) data;
+ (Samples*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Samples*) parseFromInputStream:(NSInputStream*) input;
+ (Samples*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Samples*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Samples*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Samples_Builder : PBGeneratedMessage_Builder {
@private
  Samples* result;
}

- (Samples*) defaultInstance;

- (Samples_Builder*) clear;
- (Samples_Builder*) clone;

- (Samples*) build;
- (Samples*) buildPartial;

- (Samples_Builder*) mergeFrom:(Samples*) other;
- (Samples_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Samples_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) sampleList;
- (Sample*) sampleAtIndex:(int32_t) index;
- (Samples_Builder*) replaceSampleAtIndex:(int32_t) index with:(Sample*) value;
- (Samples_Builder*) addSample:(Sample*) value;
- (Samples_Builder*) addAllSample:(NSArray*) values;
- (Samples_Builder*) clearSampleList;
@end

