/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import "Thrift/protocol/TProtocol.h"
#import "Thrift/TApplicationException.h"
#import "Thrift/protocol/TProtocolUtil.h"
#import "Thrift/TProcessor.h"

#import "CaratProtocol.h"


@implementation CaratProtocolConstants
+ (void) initialize {
}
@end

@implementation Registration

- (id) initWithUuId: (NSString *) uuId platformId: (NSString *) platformId systemVersion: (NSString *) systemVersion
{
  self = [super init];
  __uuId = [uuId retain];
  __uuId_isset = YES;
  __platformId = [platformId retain];
  __platformId_isset = YES;
  __systemVersion = [systemVersion retain];
  __systemVersion_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"uuId"])
  {
    __uuId = [[decoder decodeObjectForKey: @"uuId"] retain];
    __uuId_isset = YES;
  }
  if ([decoder containsValueForKey: @"platformId"])
  {
    __platformId = [[decoder decodeObjectForKey: @"platformId"] retain];
    __platformId_isset = YES;
  }
  if ([decoder containsValueForKey: @"systemVersion"])
  {
    __systemVersion = [[decoder decodeObjectForKey: @"systemVersion"] retain];
    __systemVersion_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__uuId_isset)
  {
    [encoder encodeObject: __uuId forKey: @"uuId"];
  }
  if (__platformId_isset)
  {
    [encoder encodeObject: __platformId forKey: @"platformId"];
  }
  if (__systemVersion_isset)
  {
    [encoder encodeObject: __systemVersion forKey: @"systemVersion"];
  }
}

- (void) dealloc
{
  [__uuId release];
  [__platformId release];
  [__systemVersion release];
  [super dealloc];
}

- (NSString *) uuId {
  return [[__uuId retain] autorelease];
}

- (void) setUuId: (NSString *) uuId {
  [uuId retain];
  [__uuId release];
  __uuId = uuId;
  __uuId_isset = YES;
}

- (BOOL) uuIdIsSet {
  return __uuId_isset;
}

- (void) unsetUuId {
  [__uuId release];
  __uuId = nil;
  __uuId_isset = NO;
}

- (NSString *) platformId {
  return [[__platformId retain] autorelease];
}

- (void) setPlatformId: (NSString *) platformId {
  [platformId retain];
  [__platformId release];
  __platformId = platformId;
  __platformId_isset = YES;
}

- (BOOL) platformIdIsSet {
  return __platformId_isset;
}

- (void) unsetPlatformId {
  [__platformId release];
  __platformId = nil;
  __platformId_isset = NO;
}

- (NSString *) systemVersion {
  return [[__systemVersion retain] autorelease];
}

- (void) setSystemVersion: (NSString *) systemVersion {
  [systemVersion retain];
  [__systemVersion release];
  __systemVersion = systemVersion;
  __systemVersion_isset = YES;
}

- (BOOL) systemVersionIsSet {
  return __systemVersion_isset;
}

- (void) unsetSystemVersion {
  [__systemVersion release];
  __systemVersion = nil;
  __systemVersion_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setUuId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setPlatformId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setSystemVersion: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Registration"];
  if (__uuId_isset) {
    if (__uuId != nil) {
      [outProtocol writeFieldBeginWithName: @"uuId" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __uuId];
      [outProtocol writeFieldEnd];
    }
  }
  if (__platformId_isset) {
    if (__platformId != nil) {
      [outProtocol writeFieldBeginWithName: @"platformId" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __platformId];
      [outProtocol writeFieldEnd];
    }
  }
  if (__systemVersion_isset) {
    if (__systemVersion != nil) {
      [outProtocol writeFieldBeginWithName: @"systemVersion" type: TType_STRING fieldID: 3];
      [outProtocol writeString: __systemVersion];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Registration("];
  [ms appendString: @"uuId:"];
  [ms appendFormat: @"\"%@\"", __uuId];
  [ms appendString: @",platformId:"];
  [ms appendFormat: @"\"%@\"", __platformId];
  [ms appendString: @",systemVersion:"];
  [ms appendFormat: @"\"%@\"", __systemVersion];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation ProcessInfo

- (id) initWithPId: (int32_t) pId pName: (NSString *) pName
{
  self = [super init];
  __pId = pId;
  __pId_isset = YES;
  __pName = [pName retain];
  __pName_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"pId"])
  {
    __pId = [decoder decodeInt32ForKey: @"pId"];
    __pId_isset = YES;
  }
  if ([decoder containsValueForKey: @"pName"])
  {
    __pName = [[decoder decodeObjectForKey: @"pName"] retain];
    __pName_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__pId_isset)
  {
    [encoder encodeInt32: __pId forKey: @"pId"];
  }
  if (__pName_isset)
  {
    [encoder encodeObject: __pName forKey: @"pName"];
  }
}

- (void) dealloc
{
  [__pName release];
  [super dealloc];
}

- (int32_t) pId {
  return __pId;
}

- (void) setPId: (int32_t) pId {
  __pId = pId;
  __pId_isset = YES;
}

- (BOOL) pIdIsSet {
  return __pId_isset;
}

- (void) unsetPId {
  __pId_isset = NO;
}

- (NSString *) pName {
  return [[__pName retain] autorelease];
}

- (void) setPName: (NSString *) pName {
  [pName retain];
  [__pName release];
  __pName = pName;
  __pName_isset = YES;
}

- (BOOL) pNameIsSet {
  return __pName_isset;
}

- (void) unsetPName {
  [__pName release];
  __pName = nil;
  __pName_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setPId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setPName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"ProcessInfo"];
  if (__pId_isset) {
    [outProtocol writeFieldBeginWithName: @"pId" type: TType_I32 fieldID: 1];
    [outProtocol writeI32: __pId];
    [outProtocol writeFieldEnd];
  }
  if (__pName_isset) {
    if (__pName != nil) {
      [outProtocol writeFieldBeginWithName: @"pName" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __pName];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"ProcessInfo("];
  [ms appendString: @"pId:"];
  [ms appendFormat: @"%i", __pId];
  [ms appendString: @",pName:"];
  [ms appendFormat: @"\"%@\"", __pName];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation Sample

- (id) initWithUuId: (NSString *) uuId timestamp: (int32_t) timestamp piList: (ProcessInfoList) piList batteryState: (int16_t) batteryState batteryLevel: (double) batteryLevel memoryWired: (int32_t) memoryWired memoryActive: (int32_t) memoryActive memoryInactive: (int32_t) memoryInactive memoryFree: (int32_t) memoryFree memoryUser: (int32_t) memoryUser triggeredBy: (NSString *) triggeredBy
{
  self = [super init];
  __uuId = [uuId retain];
  __uuId_isset = YES;
  __timestamp = timestamp;
  __timestamp_isset = YES;
  __piList = [piList retain];
  __piList_isset = YES;
  __batteryState = batteryState;
  __batteryState_isset = YES;
  __batteryLevel = batteryLevel;
  __batteryLevel_isset = YES;
  __memoryWired = memoryWired;
  __memoryWired_isset = YES;
  __memoryActive = memoryActive;
  __memoryActive_isset = YES;
  __memoryInactive = memoryInactive;
  __memoryInactive_isset = YES;
  __memoryFree = memoryFree;
  __memoryFree_isset = YES;
  __memoryUser = memoryUser;
  __memoryUser_isset = YES;
  __triggeredBy = [triggeredBy retain];
  __triggeredBy_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"uuId"])
  {
    __uuId = [[decoder decodeObjectForKey: @"uuId"] retain];
    __uuId_isset = YES;
  }
  if ([decoder containsValueForKey: @"timestamp"])
  {
    __timestamp = [decoder decodeInt32ForKey: @"timestamp"];
    __timestamp_isset = YES;
  }
  if ([decoder containsValueForKey: @"piList"])
  {
    __piList = [[decoder decodeObjectForKey: @"piList"] retain];
    __piList_isset = YES;
  }
  if ([decoder containsValueForKey: @"batteryState"])
  {
    __batteryState = [decoder decodeIntForKey: @"batteryState"];
    __batteryState_isset = YES;
  }
  if ([decoder containsValueForKey: @"batteryLevel"])
  {
    __batteryLevel = [decoder decodeDoubleForKey: @"batteryLevel"];
    __batteryLevel_isset = YES;
  }
  if ([decoder containsValueForKey: @"memoryWired"])
  {
    __memoryWired = [decoder decodeInt32ForKey: @"memoryWired"];
    __memoryWired_isset = YES;
  }
  if ([decoder containsValueForKey: @"memoryActive"])
  {
    __memoryActive = [decoder decodeInt32ForKey: @"memoryActive"];
    __memoryActive_isset = YES;
  }
  if ([decoder containsValueForKey: @"memoryInactive"])
  {
    __memoryInactive = [decoder decodeInt32ForKey: @"memoryInactive"];
    __memoryInactive_isset = YES;
  }
  if ([decoder containsValueForKey: @"memoryFree"])
  {
    __memoryFree = [decoder decodeInt32ForKey: @"memoryFree"];
    __memoryFree_isset = YES;
  }
  if ([decoder containsValueForKey: @"memoryUser"])
  {
    __memoryUser = [decoder decodeInt32ForKey: @"memoryUser"];
    __memoryUser_isset = YES;
  }
  if ([decoder containsValueForKey: @"triggeredBy"])
  {
    __triggeredBy = [[decoder decodeObjectForKey: @"triggeredBy"] retain];
    __triggeredBy_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__uuId_isset)
  {
    [encoder encodeObject: __uuId forKey: @"uuId"];
  }
  if (__timestamp_isset)
  {
    [encoder encodeInt32: __timestamp forKey: @"timestamp"];
  }
  if (__piList_isset)
  {
    [encoder encodeObject: __piList forKey: @"piList"];
  }
  if (__batteryState_isset)
  {
    [encoder encodeInt: __batteryState forKey: @"batteryState"];
  }
  if (__batteryLevel_isset)
  {
    [encoder encodeDouble: __batteryLevel forKey: @"batteryLevel"];
  }
  if (__memoryWired_isset)
  {
    [encoder encodeInt32: __memoryWired forKey: @"memoryWired"];
  }
  if (__memoryActive_isset)
  {
    [encoder encodeInt32: __memoryActive forKey: @"memoryActive"];
  }
  if (__memoryInactive_isset)
  {
    [encoder encodeInt32: __memoryInactive forKey: @"memoryInactive"];
  }
  if (__memoryFree_isset)
  {
    [encoder encodeInt32: __memoryFree forKey: @"memoryFree"];
  }
  if (__memoryUser_isset)
  {
    [encoder encodeInt32: __memoryUser forKey: @"memoryUser"];
  }
  if (__triggeredBy_isset)
  {
    [encoder encodeObject: __triggeredBy forKey: @"triggeredBy"];
  }
}

- (void) dealloc
{
  [__uuId release];
  [__piList release];
  [__triggeredBy release];
  [super dealloc];
}

- (NSString *) uuId {
  return [[__uuId retain] autorelease];
}

- (void) setUuId: (NSString *) uuId {
  [uuId retain];
  [__uuId release];
  __uuId = uuId;
  __uuId_isset = YES;
}

- (BOOL) uuIdIsSet {
  return __uuId_isset;
}

- (void) unsetUuId {
  [__uuId release];
  __uuId = nil;
  __uuId_isset = NO;
}

- (int32_t) timestamp {
  return __timestamp;
}

- (void) setTimestamp: (int32_t) timestamp {
  __timestamp = timestamp;
  __timestamp_isset = YES;
}

- (BOOL) timestampIsSet {
  return __timestamp_isset;
}

- (void) unsetTimestamp {
  __timestamp_isset = NO;
}

- (NSArray *) piList {
  return [[__piList retain] autorelease];
}

- (void) setPiList: (NSArray *) piList {
  [piList retain];
  [__piList release];
  __piList = piList;
  __piList_isset = YES;
}

- (BOOL) piListIsSet {
  return __piList_isset;
}

- (void) unsetPiList {
  [__piList release];
  __piList = nil;
  __piList_isset = NO;
}

- (int16_t) batteryState {
  return __batteryState;
}

- (void) setBatteryState: (int16_t) batteryState {
  __batteryState = batteryState;
  __batteryState_isset = YES;
}

- (BOOL) batteryStateIsSet {
  return __batteryState_isset;
}

- (void) unsetBatteryState {
  __batteryState_isset = NO;
}

- (double) batteryLevel {
  return __batteryLevel;
}

- (void) setBatteryLevel: (double) batteryLevel {
  __batteryLevel = batteryLevel;
  __batteryLevel_isset = YES;
}

- (BOOL) batteryLevelIsSet {
  return __batteryLevel_isset;
}

- (void) unsetBatteryLevel {
  __batteryLevel_isset = NO;
}

- (int32_t) memoryWired {
  return __memoryWired;
}

- (void) setMemoryWired: (int32_t) memoryWired {
  __memoryWired = memoryWired;
  __memoryWired_isset = YES;
}

- (BOOL) memoryWiredIsSet {
  return __memoryWired_isset;
}

- (void) unsetMemoryWired {
  __memoryWired_isset = NO;
}

- (int32_t) memoryActive {
  return __memoryActive;
}

- (void) setMemoryActive: (int32_t) memoryActive {
  __memoryActive = memoryActive;
  __memoryActive_isset = YES;
}

- (BOOL) memoryActiveIsSet {
  return __memoryActive_isset;
}

- (void) unsetMemoryActive {
  __memoryActive_isset = NO;
}

- (int32_t) memoryInactive {
  return __memoryInactive;
}

- (void) setMemoryInactive: (int32_t) memoryInactive {
  __memoryInactive = memoryInactive;
  __memoryInactive_isset = YES;
}

- (BOOL) memoryInactiveIsSet {
  return __memoryInactive_isset;
}

- (void) unsetMemoryInactive {
  __memoryInactive_isset = NO;
}

- (int32_t) memoryFree {
  return __memoryFree;
}

- (void) setMemoryFree: (int32_t) memoryFree {
  __memoryFree = memoryFree;
  __memoryFree_isset = YES;
}

- (BOOL) memoryFreeIsSet {
  return __memoryFree_isset;
}

- (void) unsetMemoryFree {
  __memoryFree_isset = NO;
}

- (int32_t) memoryUser {
  return __memoryUser;
}

- (void) setMemoryUser: (int32_t) memoryUser {
  __memoryUser = memoryUser;
  __memoryUser_isset = YES;
}

- (BOOL) memoryUserIsSet {
  return __memoryUser_isset;
}

- (void) unsetMemoryUser {
  __memoryUser_isset = NO;
}

- (NSString *) triggeredBy {
  return [[__triggeredBy retain] autorelease];
}

- (void) setTriggeredBy: (NSString *) triggeredBy {
  [triggeredBy retain];
  [__triggeredBy release];
  __triggeredBy = triggeredBy;
  __triggeredBy_isset = YES;
}

- (BOOL) triggeredByIsSet {
  return __triggeredBy_isset;
}

- (void) unsetTriggeredBy {
  [__triggeredBy release];
  __triggeredBy = nil;
  __triggeredBy_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setUuId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setTimestamp: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_LIST) {
          int _size0;
          [inProtocol readListBeginReturningElementType: NULL size: &_size0];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size0];
          int _i1;
          for (_i1 = 0; _i1 < _size0; ++_i1)
          {
            ProcessInfo *_elem2 = [[ProcessInfo alloc] init];
            [_elem2 read: inProtocol];
            [fieldValue addObject: _elem2];
            [_elem2 release];
          }
          [inProtocol readListEnd];
          [self setPiList: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_I16) {
          int16_t fieldValue = [inProtocol readI16];
          [self setBatteryState: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 5:
        if (fieldType == TType_DOUBLE) {
          double fieldValue = [inProtocol readDouble];
          [self setBatteryLevel: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 6:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setMemoryWired: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 7:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setMemoryActive: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 8:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setMemoryInactive: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 9:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setMemoryFree: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 10:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setMemoryUser: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 11:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setTriggeredBy: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Sample"];
  if (__uuId_isset) {
    if (__uuId != nil) {
      [outProtocol writeFieldBeginWithName: @"uuId" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __uuId];
      [outProtocol writeFieldEnd];
    }
  }
  if (__timestamp_isset) {
    [outProtocol writeFieldBeginWithName: @"timestamp" type: TType_I32 fieldID: 2];
    [outProtocol writeI32: __timestamp];
    [outProtocol writeFieldEnd];
  }
  if (__piList_isset) {
    if (__piList != nil) {
      [outProtocol writeFieldBeginWithName: @"piList" type: TType_LIST fieldID: 3];
      {
        [outProtocol writeListBeginWithElementType: TType_STRUCT size: [__piList count]];
        int i4;
        for (i4 = 0; i4 < [__piList count]; i4++)
        {
          [[__piList objectAtIndex: i4] write: outProtocol];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  if (__batteryState_isset) {
    [outProtocol writeFieldBeginWithName: @"batteryState" type: TType_I16 fieldID: 4];
    [outProtocol writeI16: __batteryState];
    [outProtocol writeFieldEnd];
  }
  if (__batteryLevel_isset) {
    [outProtocol writeFieldBeginWithName: @"batteryLevel" type: TType_DOUBLE fieldID: 5];
    [outProtocol writeDouble: __batteryLevel];
    [outProtocol writeFieldEnd];
  }
  if (__memoryWired_isset) {
    [outProtocol writeFieldBeginWithName: @"memoryWired" type: TType_I32 fieldID: 6];
    [outProtocol writeI32: __memoryWired];
    [outProtocol writeFieldEnd];
  }
  if (__memoryActive_isset) {
    [outProtocol writeFieldBeginWithName: @"memoryActive" type: TType_I32 fieldID: 7];
    [outProtocol writeI32: __memoryActive];
    [outProtocol writeFieldEnd];
  }
  if (__memoryInactive_isset) {
    [outProtocol writeFieldBeginWithName: @"memoryInactive" type: TType_I32 fieldID: 8];
    [outProtocol writeI32: __memoryInactive];
    [outProtocol writeFieldEnd];
  }
  if (__memoryFree_isset) {
    [outProtocol writeFieldBeginWithName: @"memoryFree" type: TType_I32 fieldID: 9];
    [outProtocol writeI32: __memoryFree];
    [outProtocol writeFieldEnd];
  }
  if (__memoryUser_isset) {
    [outProtocol writeFieldBeginWithName: @"memoryUser" type: TType_I32 fieldID: 10];
    [outProtocol writeI32: __memoryUser];
    [outProtocol writeFieldEnd];
  }
  if (__triggeredBy_isset) {
    if (__triggeredBy != nil) {
      [outProtocol writeFieldBeginWithName: @"triggeredBy" type: TType_STRING fieldID: 11];
      [outProtocol writeString: __triggeredBy];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Sample("];
  [ms appendString: @"uuId:"];
  [ms appendFormat: @"\"%@\"", __uuId];
  [ms appendString: @",timestamp:"];
  [ms appendFormat: @"%i", __timestamp];
  [ms appendString: @",piList:"];
  [ms appendFormat: @"%@", __piList];
  [ms appendString: @",batteryState:"];
  [ms appendFormat: @"%hi", __batteryState];
  [ms appendString: @",batteryLevel:"];
  [ms appendFormat: @"%f", __batteryLevel];
  [ms appendString: @",memoryWired:"];
  [ms appendFormat: @"%i", __memoryWired];
  [ms appendString: @",memoryActive:"];
  [ms appendFormat: @"%i", __memoryActive];
  [ms appendString: @",memoryInactive:"];
  [ms appendFormat: @"%i", __memoryInactive];
  [ms appendString: @",memoryFree:"];
  [ms appendFormat: @"%i", __memoryFree];
  [ms appendString: @",memoryUser:"];
  [ms appendFormat: @"%i", __memoryUser];
  [ms appendString: @",triggeredBy:"];
  [ms appendFormat: @"\"%@\"", __triggeredBy];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation DetailScreenReport

- (id) initWithScore: (double) score xVals: (NSArray *) xVals yVals: (NSArray *) yVals
{
  self = [super init];
  __score = score;
  __score_isset = YES;
  __xVals = [xVals retain];
  __xVals_isset = YES;
  __yVals = [yVals retain];
  __yVals_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"score"])
  {
    __score = [decoder decodeDoubleForKey: @"score"];
    __score_isset = YES;
  }
  if ([decoder containsValueForKey: @"xVals"])
  {
    __xVals = [[decoder decodeObjectForKey: @"xVals"] retain];
    __xVals_isset = YES;
  }
  if ([decoder containsValueForKey: @"yVals"])
  {
    __yVals = [[decoder decodeObjectForKey: @"yVals"] retain];
    __yVals_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__score_isset)
  {
    [encoder encodeDouble: __score forKey: @"score"];
  }
  if (__xVals_isset)
  {
    [encoder encodeObject: __xVals forKey: @"xVals"];
  }
  if (__yVals_isset)
  {
    [encoder encodeObject: __yVals forKey: @"yVals"];
  }
}

- (void) dealloc
{
  [__xVals release];
  [__yVals release];
  [super dealloc];
}

- (double) score {
  return __score;
}

- (void) setScore: (double) score {
    if (score < 0) { score = 0; }
    else if (score > 1) { score = 1; }
  __score = score;
  __score_isset = YES;
}

- (BOOL) scoreIsSet {
  return __score_isset;
}

- (void) unsetScore {
  __score_isset = NO;
}

- (NSArray *) xVals {
  return [[__xVals retain] autorelease];
}

- (void) setXVals: (NSArray *) xVals {
  [xVals retain];
  [__xVals release];
  __xVals = xVals;
  __xVals_isset = YES;
}

- (BOOL) xValsIsSet {
  return __xVals_isset;
}

- (void) unsetXVals {
  [__xVals release];
  __xVals = nil;
  __xVals_isset = NO;
}

- (NSArray *) yVals {
  return [[__yVals retain] autorelease];
}

- (void) setYVals: (NSArray *) yVals {
  [yVals retain];
  [__yVals release];
  __yVals = yVals;
  __yVals_isset = YES;
}

- (BOOL) yValsIsSet {
  return __yVals_isset;
}

- (void) unsetYVals {
  [__yVals release];
  __yVals = nil;
  __yVals_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_DOUBLE) {
          double fieldValue = [inProtocol readDouble];
          [self setScore: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_LIST) {
          int _size5;
          [inProtocol readListBeginReturningElementType: NULL size: &_size5];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size5];
          int _i6;
          for (_i6 = 0; _i6 < _size5; ++_i6)
          {
            double _elem7 = [inProtocol readDouble];
            [fieldValue addObject: [NSNumber numberWithDouble: _elem7]];
          }
          [inProtocol readListEnd];
          [self setXVals: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_LIST) {
          int _size8;
          [inProtocol readListBeginReturningElementType: NULL size: &_size8];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size8];
          int _i9;
          for (_i9 = 0; _i9 < _size8; ++_i9)
          {
            double _elem10 = [inProtocol readDouble];
            [fieldValue addObject: [NSNumber numberWithDouble: _elem10]];
          }
          [inProtocol readListEnd];
          [self setYVals: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"DetailScreenReport"];
  if (__score_isset) {
    [outProtocol writeFieldBeginWithName: @"score" type: TType_DOUBLE fieldID: 1];
    [outProtocol writeDouble: __score];
    [outProtocol writeFieldEnd];
  }
  if (__xVals_isset) {
    if (__xVals != nil) {
      [outProtocol writeFieldBeginWithName: @"xVals" type: TType_LIST fieldID: 2];
      {
        [outProtocol writeListBeginWithElementType: TType_DOUBLE size: [__xVals count]];
        int i12;
        for (i12 = 0; i12 < [__xVals count]; i12++)
        {
          [outProtocol writeDouble: [[__xVals objectAtIndex: i12] doubleValue]];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  if (__yVals_isset) {
    if (__yVals != nil) {
      [outProtocol writeFieldBeginWithName: @"yVals" type: TType_LIST fieldID: 3];
      {
        [outProtocol writeListBeginWithElementType: TType_DOUBLE size: [__yVals count]];
        int i14;
        for (i14 = 0; i14 < [__yVals count]; i14++)
        {
          [outProtocol writeDouble: [[__yVals objectAtIndex: i14] doubleValue]];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"DetailScreenReport("];
  [ms appendString: @"score:"];
  [ms appendFormat: @"%f", __score];
  [ms appendString: @",xVals:"];
  [ms appendFormat: @"%@", __xVals];
  [ms appendString: @",yVals:"];
  [ms appendFormat: @"%@", __yVals];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation HogsBugs

- (id) initWithPId: (int16_t) pId pName: (NSString *) pName wDistance: (double) wDistance pdfXVals: (NSArray *) pdfXVals pdfYVals: (NSArray *) pdfYVals
{
  self = [super init];
  __pId = pId;
  __pId_isset = YES;
  __pName = [pName retain];
  __pName_isset = YES;
  __wDistance = wDistance;
  __wDistance_isset = YES;
  __pdfXVals = [pdfXVals retain];
  __pdfXVals_isset = YES;
  __pdfYVals = [pdfYVals retain];
  __pdfYVals_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"pId"])
  {
    __pId = [decoder decodeIntForKey: @"pId"];
    __pId_isset = YES;
  }
  if ([decoder containsValueForKey: @"pName"])
  {
    __pName = [[decoder decodeObjectForKey: @"pName"] retain];
    __pName_isset = YES;
  }
  if ([decoder containsValueForKey: @"wDistance"])
  {
    __wDistance = [decoder decodeDoubleForKey: @"wDistance"];
    __wDistance_isset = YES;
  }
  if ([decoder containsValueForKey: @"pdfXVals"])
  {
    __pdfXVals = [[decoder decodeObjectForKey: @"pdfXVals"] retain];
    __pdfXVals_isset = YES;
  }
  if ([decoder containsValueForKey: @"pdfYVals"])
  {
    __pdfYVals = [[decoder decodeObjectForKey: @"pdfYVals"] retain];
    __pdfYVals_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__pId_isset)
  {
    [encoder encodeInt: __pId forKey: @"pId"];
  }
  if (__pName_isset)
  {
    [encoder encodeObject: __pName forKey: @"pName"];
  }
  if (__wDistance_isset)
  {
    [encoder encodeDouble: __wDistance forKey: @"wDistance"];
  }
  if (__pdfXVals_isset)
  {
    [encoder encodeObject: __pdfXVals forKey: @"pdfXVals"];
  }
  if (__pdfYVals_isset)
  {
    [encoder encodeObject: __pdfYVals forKey: @"pdfYVals"];
  }
}

- (void) dealloc
{
  [__pName release];
  [__pdfXVals release];
  [__pdfYVals release];
  [super dealloc];
}

- (int16_t) pId {
  return __pId;
}

- (void) setPId: (int16_t) pId {
  __pId = pId;
  __pId_isset = YES;
}

- (BOOL) pIdIsSet {
  return __pId_isset;
}

- (void) unsetPId {
  __pId_isset = NO;
}

- (NSString *) pName {
  return [[__pName retain] autorelease];
}

- (void) setPName: (NSString *) pName {
  [pName retain];
  [__pName release];
  __pName = pName;
  __pName_isset = YES;
}

- (BOOL) pNameIsSet {
  return __pName_isset;
}

- (void) unsetPName {
  [__pName release];
  __pName = nil;
  __pName_isset = NO;
}

- (double) wDistance {
  return __wDistance;
}

- (void) setWDistance: (double) wDistance {
  __wDistance = wDistance;
  __wDistance_isset = YES;
}

- (BOOL) wDistanceIsSet {
  return __wDistance_isset;
}

- (void) unsetWDistance {
  __wDistance_isset = NO;
}

- (NSArray *) pdfXVals {
  return [[__pdfXVals retain] autorelease];
}

- (void) setPdfXVals: (NSArray *) pdfXVals {
  [pdfXVals retain];
  [__pdfXVals release];
  __pdfXVals = pdfXVals;
  __pdfXVals_isset = YES;
}

- (BOOL) pdfXValsIsSet {
  return __pdfXVals_isset;
}

- (void) unsetPdfXVals {
  [__pdfXVals release];
  __pdfXVals = nil;
  __pdfXVals_isset = NO;
}

- (NSArray *) pdfYVals {
  return [[__pdfYVals retain] autorelease];
}

- (void) setPdfYVals: (NSArray *) pdfYVals {
  [pdfYVals retain];
  [__pdfYVals release];
  __pdfYVals = pdfYVals;
  __pdfYVals_isset = YES;
}

- (BOOL) pdfYValsIsSet {
  return __pdfYVals_isset;
}

- (void) unsetPdfYVals {
  [__pdfYVals release];
  __pdfYVals = nil;
  __pdfYVals_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I16) {
          int16_t fieldValue = [inProtocol readI16];
          [self setPId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setPName: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_DOUBLE) {
          double fieldValue = [inProtocol readDouble];
          [self setWDistance: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_LIST) {
          int _size15;
          [inProtocol readListBeginReturningElementType: NULL size: &_size15];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size15];
          int _i16;
          for (_i16 = 0; _i16 < _size15; ++_i16)
          {
            double _elem17 = [inProtocol readDouble];
            [fieldValue addObject: [NSNumber numberWithDouble: _elem17]];
          }
          [inProtocol readListEnd];
          [self setPdfXVals: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 5:
        if (fieldType == TType_LIST) {
          int _size18;
          [inProtocol readListBeginReturningElementType: NULL size: &_size18];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size18];
          int _i19;
          for (_i19 = 0; _i19 < _size18; ++_i19)
          {
            double _elem20 = [inProtocol readDouble];
            [fieldValue addObject: [NSNumber numberWithDouble: _elem20]];
          }
          [inProtocol readListEnd];
          [self setPdfYVals: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"HogsBugs"];
  if (__pId_isset) {
    [outProtocol writeFieldBeginWithName: @"pId" type: TType_I16 fieldID: 1];
    [outProtocol writeI16: __pId];
    [outProtocol writeFieldEnd];
  }
  if (__pName_isset) {
    if (__pName != nil) {
      [outProtocol writeFieldBeginWithName: @"pName" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __pName];
      [outProtocol writeFieldEnd];
    }
  }
  if (__wDistance_isset) {
    [outProtocol writeFieldBeginWithName: @"wDistance" type: TType_DOUBLE fieldID: 3];
    [outProtocol writeDouble: __wDistance];
    [outProtocol writeFieldEnd];
  }
  if (__pdfXVals_isset) {
    if (__pdfXVals != nil) {
      [outProtocol writeFieldBeginWithName: @"pdfXVals" type: TType_LIST fieldID: 4];
      {
        [outProtocol writeListBeginWithElementType: TType_DOUBLE size: [__pdfXVals count]];
        int i22;
        for (i22 = 0; i22 < [__pdfXVals count]; i22++)
        {
          [outProtocol writeDouble: [[__pdfXVals objectAtIndex: i22] doubleValue]];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  if (__pdfYVals_isset) {
    if (__pdfYVals != nil) {
      [outProtocol writeFieldBeginWithName: @"pdfYVals" type: TType_LIST fieldID: 5];
      {
        [outProtocol writeListBeginWithElementType: TType_DOUBLE size: [__pdfYVals count]];
        int i24;
        for (i24 = 0; i24 < [__pdfYVals count]; i24++)
        {
          [outProtocol writeDouble: [[__pdfYVals objectAtIndex: i24] doubleValue]];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"HogsBugs("];
  [ms appendString: @"pId:"];
  [ms appendFormat: @"%hi", __pId];
  [ms appendString: @",pName:"];
  [ms appendFormat: @"\"%@\"", __pName];
  [ms appendString: @",wDistance:"];
  [ms appendFormat: @"%f", __wDistance];
  [ms appendString: @",pdfXVals:"];
  [ms appendFormat: @"%@", __pdfXVals];
  [ms appendString: @",pdfYVals:"];
  [ms appendFormat: @"%@", __pdfYVals];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation HogBugReport

- (id) initWithUuId: (NSString *) uuId hbList: (HogsBugsList) hbList
{
  self = [super init];
  __uuId = [uuId retain];
  __uuId_isset = YES;
  __hbList = [hbList retain];
  __hbList_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"uuId"])
  {
    __uuId = [[decoder decodeObjectForKey: @"uuId"] retain];
    __uuId_isset = YES;
  }
  if ([decoder containsValueForKey: @"hbList"])
  {
    __hbList = [[decoder decodeObjectForKey: @"hbList"] retain];
    __hbList_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__uuId_isset)
  {
    [encoder encodeObject: __uuId forKey: @"uuId"];
  }
  if (__hbList_isset)
  {
    [encoder encodeObject: __hbList forKey: @"hbList"];
  }
}

- (void) dealloc
{
  [__uuId release];
  [__hbList release];
  [super dealloc];
}

- (NSString *) uuId {
  return [[__uuId retain] autorelease];
}

- (void) setUuId: (NSString *) uuId {
  [uuId retain];
  [__uuId release];
  __uuId = uuId;
  __uuId_isset = YES;
}

- (BOOL) uuIdIsSet {
  return __uuId_isset;
}

- (void) unsetUuId {
  [__uuId release];
  __uuId = nil;
  __uuId_isset = NO;
}

- (NSArray *) hbList {
  return [[__hbList retain] autorelease];
}

- (void) setHbList: (NSArray *) hbList {
  [hbList retain];
  [__hbList release];
  __hbList = hbList;
  __hbList_isset = YES;
}

- (BOOL) hbListIsSet {
  return __hbList_isset;
}

- (void) unsetHbList {
  [__hbList release];
  __hbList = nil;
  __hbList_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setUuId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_LIST) {
          int _size25;
          [inProtocol readListBeginReturningElementType: NULL size: &_size25];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size25];
          int _i26;
          for (_i26 = 0; _i26 < _size25; ++_i26)
          {
            HogsBugs *_elem27 = [[HogsBugs alloc] init];
            [_elem27 read: inProtocol];
            [fieldValue addObject: _elem27];
            [_elem27 release];
          }
          [inProtocol readListEnd];
          [self setHbList: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"HogBugReport"];
  if (__uuId_isset) {
    if (__uuId != nil) {
      [outProtocol writeFieldBeginWithName: @"uuId" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __uuId];
      [outProtocol writeFieldEnd];
    }
  }
  if (__hbList_isset) {
    if (__hbList != nil) {
      [outProtocol writeFieldBeginWithName: @"hbList" type: TType_LIST fieldID: 2];
      {
        [outProtocol writeListBeginWithElementType: TType_STRUCT size: [__hbList count]];
        int i29;
        for (i29 = 0; i29 < [__hbList count]; i29++)
        {
          [[__hbList objectAtIndex: i29] write: outProtocol];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"HogBugReport("];
  [ms appendString: @"uuId:"];
  [ms appendFormat: @"\"%@\"", __uuId];
  [ms appendString: @",hbList:"];
  [ms appendFormat: @"%@", __hbList];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation Feature

- (id) initWithKey: (NSString *) key value: (NSString *) value
{
  self = [super init];
  __key = [key retain];
  __key_isset = YES;
  __value = [value retain];
  __value_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"key"])
  {
    __key = [[decoder decodeObjectForKey: @"key"] retain];
    __key_isset = YES;
  }
  if ([decoder containsValueForKey: @"value"])
  {
    __value = [[decoder decodeObjectForKey: @"value"] retain];
    __value_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__key_isset)
  {
    [encoder encodeObject: __key forKey: @"key"];
  }
  if (__value_isset)
  {
    [encoder encodeObject: __value forKey: @"value"];
  }
}

- (void) dealloc
{
  [__key release];
  [__value release];
  [super dealloc];
}

- (NSString *) key {
  return [[__key retain] autorelease];
}

- (void) setKey: (NSString *) key {
  [key retain];
  [__key release];
  __key = key;
  __key_isset = YES;
}

- (BOOL) keyIsSet {
  return __key_isset;
}

- (void) unsetKey {
  [__key release];
  __key = nil;
  __key_isset = NO;
}

- (NSString *) value {
  return [[__value retain] autorelease];
}

- (void) setValue: (NSString *) value {
  [value retain];
  [__value release];
  __value = value;
  __value_isset = YES;
}

- (BOOL) valueIsSet {
  return __value_isset;
}

- (void) unsetValue {
  [__value release];
  __value = nil;
  __value_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setKey: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setValue: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"Feature"];
  if (__key_isset) {
    if (__key != nil) {
      [outProtocol writeFieldBeginWithName: @"key" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __key];
      [outProtocol writeFieldEnd];
    }
  }
  if (__value_isset) {
    if (__value != nil) {
      [outProtocol writeFieldBeginWithName: @"value" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __value];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"Feature("];
  [ms appendString: @"key:"];
  [ms appendFormat: @"\"%@\"", __key];
  [ms appendString: @",value:"];
  [ms appendFormat: @"\"%@\"", __value];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface registerMe_args : NSObject <NSCoding> {
  Registration * __registration;

  BOOL __registration_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=registration, setter=setRegistration:) Registration * registration;
#endif

- (id) initWithRegistration: (Registration *) registration;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (Registration *) registration;
- (void) setRegistration: (Registration *) registration;
- (BOOL) registrationIsSet;

@end

@implementation registerMe_args

- (id) initWithRegistration: (Registration *) registration
{
  self = [super init];
  __registration = [registration retain];
  __registration_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"registration"])
  {
    __registration = [[decoder decodeObjectForKey: @"registration"] retain];
    __registration_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__registration_isset)
  {
    [encoder encodeObject: __registration forKey: @"registration"];
  }
}

- (void) dealloc
{
  [__registration release];
  [super dealloc];
}

- (Registration *) registration {
  return [[__registration retain] autorelease];
}

- (void) setRegistration: (Registration *) registration {
  [registration retain];
  [__registration release];
  __registration = registration;
  __registration_isset = YES;
}

- (BOOL) registrationIsSet {
  return __registration_isset;
}

- (void) unsetRegistration {
  [__registration release];
  __registration = nil;
  __registration_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRUCT) {
          Registration *fieldValue = [[Registration alloc] init];
          [fieldValue read: inProtocol];
          [self setRegistration: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"registerMe_args"];
  if (__registration_isset) {
    if (__registration != nil) {
      [outProtocol writeFieldBeginWithName: @"registration" type: TType_STRUCT fieldID: 1];
      [__registration write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"registerMe_args("];
  [ms appendString: @"registration:"];
  [ms appendFormat: @"%@", __registration];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface uploadSample_args : NSObject <NSCoding> {
  Sample * __sample;

  BOOL __sample_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=sample, setter=setSample:) Sample * sample;
#endif

- (id) initWithSample: (Sample *) sample;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (Sample *) sample;
- (void) setSample: (Sample *) sample;
- (BOOL) sampleIsSet;

@end

@implementation uploadSample_args

- (id) initWithSample: (Sample *) sample
{
  self = [super init];
  __sample = [sample retain];
  __sample_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"sample"])
  {
    __sample = [[decoder decodeObjectForKey: @"sample"] retain];
    __sample_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__sample_isset)
  {
    [encoder encodeObject: __sample forKey: @"sample"];
  }
}

- (void) dealloc
{
  [__sample release];
  [super dealloc];
}

- (Sample *) sample {
  return [[__sample retain] autorelease];
}

- (void) setSample: (Sample *) sample {
  [sample retain];
  [__sample release];
  __sample = sample;
  __sample_isset = YES;
}

- (BOOL) sampleIsSet {
  return __sample_isset;
}

- (void) unsetSample {
  [__sample release];
  __sample = nil;
  __sample_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRUCT) {
          Sample *fieldValue = [[Sample alloc] init];
          [fieldValue read: inProtocol];
          [self setSample: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"uploadSample_args"];
  if (__sample_isset) {
    if (__sample != nil) {
      [outProtocol writeFieldBeginWithName: @"sample" type: TType_STRUCT fieldID: 1];
      [__sample write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"uploadSample_args("];
  [ms appendString: @"sample:"];
  [ms appendFormat: @"%@", __sample];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface UploadSample_result : NSObject <NSCoding> {
  BOOL __success;

  BOOL __success_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=success, setter=setSuccess:) BOOL success;
#endif

- (id) initWithSuccess: (BOOL) success;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (BOOL) success;
- (void) setSuccess: (BOOL) success;
- (BOOL) successIsSet;

@end

@implementation UploadSample_result

- (id) initWithSuccess: (BOOL) success
{
  self = [super init];
  __success = success;
  __success_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [decoder decodeBoolForKey: @"success"];
    __success_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeBool: __success forKey: @"success"];
  }
}

- (void) dealloc
{
  [super dealloc];
}

- (BOOL) success {
  return __success;
}

- (void) setSuccess: (BOOL) success {
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  __success_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 0:
        if (fieldType == TType_BOOL) {
          BOOL fieldValue = [inProtocol readBool];
          [self setSuccess: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"UploadSample_result"];

  if (__success_isset) {
    [outProtocol writeFieldBeginWithName: @"success" type: TType_BOOL fieldID: 0];
    [outProtocol writeBool: __success];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"UploadSample_result("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"%i", __success];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface getHogOrBugReport_args : NSObject <NSCoding> {
  NSString * __uuId;
  FeatureList __features;

  BOOL __uuId_isset;
  BOOL __features_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=uuId, setter=setUuId:) NSString * uuId;
@property (nonatomic, retain, getter=features, setter=setFeatures:) FeatureList features;
#endif

- (id) initWithUuId: (NSString *) uuId features: (FeatureList) features;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) uuId;
- (void) setUuId: (NSString *) uuId;
- (BOOL) uuIdIsSet;

- (FeatureList) features;
- (void) setFeatures: (FeatureList) features;
- (BOOL) featuresIsSet;

@end

@implementation getHogOrBugReport_args

- (id) initWithUuId: (NSString *) uuId features: (FeatureList) features
{
  self = [super init];
  __uuId = [uuId retain];
  __uuId_isset = YES;
  __features = [features retain];
  __features_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"uuId"])
  {
    __uuId = [[decoder decodeObjectForKey: @"uuId"] retain];
    __uuId_isset = YES;
  }
  if ([decoder containsValueForKey: @"features"])
  {
    __features = [[decoder decodeObjectForKey: @"features"] retain];
    __features_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__uuId_isset)
  {
    [encoder encodeObject: __uuId forKey: @"uuId"];
  }
  if (__features_isset)
  {
    [encoder encodeObject: __features forKey: @"features"];
  }
}

- (void) dealloc
{
  [__uuId release];
  [__features release];
  [super dealloc];
}

- (NSString *) uuId {
  return [[__uuId retain] autorelease];
}

- (void) setUuId: (NSString *) uuId {
  [uuId retain];
  [__uuId release];
  __uuId = uuId;
  __uuId_isset = YES;
}

- (BOOL) uuIdIsSet {
  return __uuId_isset;
}

- (void) unsetUuId {
  [__uuId release];
  __uuId = nil;
  __uuId_isset = NO;
}

- (NSArray *) features {
  return [[__features retain] autorelease];
}

- (void) setFeatures: (NSArray *) features {
  [features retain];
  [__features release];
  __features = features;
  __features_isset = YES;
}

- (BOOL) featuresIsSet {
  return __features_isset;
}

- (void) unsetFeatures {
  [__features release];
  __features = nil;
  __features_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setUuId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_LIST) {
          int _size30;
          [inProtocol readListBeginReturningElementType: NULL size: &_size30];
          NSMutableArray * fieldValue = [[NSMutableArray alloc] initWithCapacity: _size30];
          int _i31;
          for (_i31 = 0; _i31 < _size30; ++_i31)
          {
            Feature *_elem32 = [[Feature alloc] init];
            [_elem32 read: inProtocol];
            [fieldValue addObject: _elem32];
            [_elem32 release];
          }
          [inProtocol readListEnd];
          [self setFeatures: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"getHogOrBugReport_args"];
  if (__uuId_isset) {
    if (__uuId != nil) {
      [outProtocol writeFieldBeginWithName: @"uuId" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __uuId];
      [outProtocol writeFieldEnd];
    }
  }
  if (__features_isset) {
    if (__features != nil) {
      [outProtocol writeFieldBeginWithName: @"features" type: TType_LIST fieldID: 2];
      {
        [outProtocol writeListBeginWithElementType: TType_STRUCT size: [__features count]];
        int i34;
        for (i34 = 0; i34 < [__features count]; i34++)
        {
          [[__features objectAtIndex: i34] write: outProtocol];
        }
        [outProtocol writeListEnd];
      }
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"getHogOrBugReport_args("];
  [ms appendString: @"uuId:"];
  [ms appendFormat: @"\"%@\"", __uuId];
  [ms appendString: @",features:"];
  [ms appendFormat: @"%@", __features];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface GetHogOrBugReport_result : NSObject <NSCoding> {
  HogBugReport * __success;

  BOOL __success_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=success, setter=setSuccess:) HogBugReport * success;
#endif

- (id) initWithSuccess: (HogBugReport *) success;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (HogBugReport *) success;
- (void) setSuccess: (HogBugReport *) success;
- (BOOL) successIsSet;

@end

@implementation GetHogOrBugReport_result

- (id) initWithSuccess: (HogBugReport *) success
{
  self = [super init];
  __success = [success retain];
  __success_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [[decoder decodeObjectForKey: @"success"] retain];
    __success_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeObject: __success forKey: @"success"];
  }
}

- (void) dealloc
{
  [__success release];
  [super dealloc];
}

- (HogBugReport *) success {
  return [[__success retain] autorelease];
}

- (void) setSuccess: (HogBugReport *) success {
  [success retain];
  [__success release];
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  [__success release];
  __success = nil;
  __success_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 0:
        if (fieldType == TType_STRUCT) {
          HogBugReport *fieldValue = [[HogBugReport alloc] init];
          [fieldValue read: inProtocol];
          [self setSuccess: fieldValue];
          [fieldValue release];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"GetHogOrBugReport_result"];

  if (__success_isset) {
    if (__success != nil) {
      [outProtocol writeFieldBeginWithName: @"success" type: TType_STRUCT fieldID: 0];
      [__success write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"GetHogOrBugReport_result("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"%@", __success];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation CaratServiceClient
- (id) initWithProtocol: (id <TProtocol>) protocol
{
  return [self initWithInProtocol: protocol outProtocol: protocol];
}

- (id) initWithInProtocol: (id <TProtocol>) anInProtocol outProtocol: (id <TProtocol>) anOutProtocol
{
  [super init];
  inProtocol = [anInProtocol retain];
  outProtocol = [anOutProtocol retain];
  return self;
}

- (void) dealloc
{
  [inProtocol release];
  [outProtocol release];
  [super dealloc];
}

- (void) send_registerMe: (Registration *) registration
{
  [outProtocol writeMessageBeginWithName: @"registerMe" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"registerMe_args"];
  if (registration != nil)  {
    [outProtocol writeFieldBeginWithName: @"registration" type: TType_STRUCT fieldID: 1];
    [registration write: outProtocol];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (void) registerMe: (Registration *) registration
{
  [self send_registerMe: registration];
}

- (void) send_uploadSample: (Sample *) sample
{
  [outProtocol writeMessageBeginWithName: @"uploadSample" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"uploadSample_args"];
  if (sample != nil)  {
    [outProtocol writeFieldBeginWithName: @"sample" type: TType_STRUCT fieldID: 1];
    [sample write: outProtocol];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (BOOL) recv_uploadSample
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  UploadSample_result * result = [[[UploadSample_result alloc] init] autorelease];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  if ([result successIsSet]) {
    return [result success];
  }
  @throw [TApplicationException exceptionWithType: TApplicationException_MISSING_RESULT
                                           reason: @"uploadSample failed: unknown result"];
}

- (BOOL) uploadSample: (Sample *) sample
{
  [self send_uploadSample: sample];
  return [self recv_uploadSample];
}

- (void) send_getHogOrBugReport: (NSString *) uuId : (FeatureList) features
{
  [outProtocol writeMessageBeginWithName: @"getHogOrBugReport" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"getHogOrBugReport_args"];
  if (uuId != nil)  {
    [outProtocol writeFieldBeginWithName: @"uuId" type: TType_STRING fieldID: 1];
    [outProtocol writeString: uuId];
    [outProtocol writeFieldEnd];
  }
  if (features != nil)  {
    [outProtocol writeFieldBeginWithName: @"features" type: TType_LIST fieldID: 2];
    {
      [outProtocol writeListBeginWithElementType: TType_STRUCT size: [features count]];
      int i36;
      for (i36 = 0; i36 < [features count]; i36++)
      {
        [[features objectAtIndex: i36] write: outProtocol];
      }
      [outProtocol writeListEnd];
    }
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (HogBugReport *) recv_getHogOrBugReport
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  GetHogOrBugReport_result * result = [[[GetHogOrBugReport_result alloc] init] autorelease];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  if ([result successIsSet]) {
    return [result success];
  }
  @throw [TApplicationException exceptionWithType: TApplicationException_MISSING_RESULT
                                           reason: @"getHogOrBugReport failed: unknown result"];
}

- (HogBugReport *) getHogOrBugReport: (NSString *) uuId : (FeatureList) features
{
  [self send_getHogOrBugReport: uuId : features];
  return [self recv_getHogOrBugReport];
}

@end

@implementation CaratServiceProcessor

- (id) initWithCaratService: (id <CaratService>) service
{
  self = [super init];
  if (!self) {
    return nil;
  }
  mService = [service retain];
  mMethodMap = [[NSMutableDictionary dictionary] retain];
  {
    SEL s = @selector(process_registerMe_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"registerMe"];
  }
  {
    SEL s = @selector(process_uploadSample_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"uploadSample"];
  }
  {
    SEL s = @selector(process_getHogOrBugReport_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"getHogOrBugReport"];
  }
  return self;
}

- (id<CaratService>) service
{
  return [[mService retain] autorelease];
}

- (BOOL) processOnInputProtocol: (id <TProtocol>) inProtocol
                 outputProtocol: (id <TProtocol>) outProtocol
{
  NSString * messageName;
  int messageType;
  int seqID;
  [inProtocol readMessageBeginReturningName: &messageName
                                       type: &messageType
                                 sequenceID: &seqID];
  NSInvocation * invocation = [mMethodMap valueForKey: messageName];
  if (invocation == nil) {
    [TProtocolUtil skipType: TType_STRUCT onProtocol: inProtocol];
    [inProtocol readMessageEnd];
    TApplicationException * x = [TApplicationException exceptionWithType: TApplicationException_UNKNOWN_METHOD reason: [NSString stringWithFormat: @"Invalid method name: '%@'", messageName]];
    [outProtocol writeMessageBeginWithName: messageName
                                      type: TMessageType_EXCEPTION
                                sequenceID: seqID];
    [x write: outProtocol];
    [outProtocol writeMessageEnd];
    [[outProtocol transport] flush];
    return YES;
  }
  // NSInvocation does not conform to NSCopying protocol
  NSInvocation * i = [NSInvocation invocationWithMethodSignature: [invocation methodSignature]];
  [i setSelector: [invocation selector]];
  [i setArgument: &seqID atIndex: 2];
  [i setArgument: &inProtocol atIndex: 3];
  [i setArgument: &outProtocol atIndex: 4];
  [i setTarget: self];
  [i invoke];
  return YES;
}

- (void) process_uploadSample_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  uploadSample_args * args = [[uploadSample_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  UploadSample_result * result = [[UploadSample_result alloc] init];
  [result setSuccess: [mService uploadSample: [args sample]]];
  [outProtocol writeMessageBeginWithName: @"uploadSample"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release];
  [args release];
}

- (void) process_getHogOrBugReport_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  getHogOrBugReport_args * args = [[getHogOrBugReport_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  GetHogOrBugReport_result * result = [[GetHogOrBugReport_result alloc] init];
  [result setSuccess: [mService getHogOrBugReport: [args uuId]: [args features]]];
  [outProtocol writeMessageBeginWithName: @"getHogOrBugReport"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release];
  [args release];
}

- (void) dealloc
{
  [mService release];
  [mMethodMap release];
  [super dealloc];
}

@end

